// Generated by https://quicktype.io

export interface Main {
    id:          string;
    Class:       string;
    Highlight:   boolean;
    Name:        string;
    Description: string;
    Price:       number;
    Meassures:   string;
    Material:    string;
    Image:       string;
}
