// Generated by https://quicktype.io
import { Main } from "./products";

export interface UserMain {
  id: string;
  Name: string;
  password: string;
  cart: Main[];
  wishlist: any[];
  email: string;
}
